[pytest]
asyncio_mode = auto

# #pytest-asyncio creates an event loop for each test
# #set the event loop scope to function (each test function/route function)
asyncio_default_fixture_loop_scope = function