"""user version unique constraint

Revision ID: 32c4aa90371d
Revises: c0d0f3d7e8bf
Create Date: 2025-02-02 23:39:10.040990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32c4aa90371d'
down_revision: Union[str, None] = 'c0d0f3d7e8bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_user_version', 'userversions', ['user_id', 'version_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_version', 'userversions', type_='unique')
    # ### end Alembic commands ###
