"""frosties deleted at column

Revision ID: 36b15a154ff1
Revises: 9874209596cb
Create Date: 2025-03-15 23:21:55.595845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36b15a154ff1'
down_revision: Union[str, None] = '9874209596cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('frosties', sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('frosties', 'deleted_at')
    # ### end Alembic commands ###
