"""remove seller id fdrom orderitems

Revision ID: 9874209596cb
Revises: 9a6d88879081
Create Date: 2025-03-09 14:31:33.912101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9874209596cb'
down_revision: Union[str, None] = '9a6d88879081'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('orderitems_seller_id_fkey', 'orderitems', type_='foreignkey')
    op.drop_column('orderitems', 'seller_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orderitems', sa.Column('seller_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_foreign_key('orderitems_seller_id_fkey', 'orderitems', 'users', ['seller_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
