"""remove goal title unique

Revision ID: 9a6d88879081
Revises: 7de8cbe65471
Create Date: 2025-02-04 23:47:04.020734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a6d88879081'
down_revision: Union[str, None] = '7de8cbe65471'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('goals_title_key', 'goals', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('goals_title_key', 'goals', ['title'])
    # ### end Alembic commands ###
