"""frosties table updates

Revision ID: bd8b827e2fd7
Revises: 32c4aa90371d
Create Date: 2025-02-03 15:39:20.506595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd8b827e2fd7'
down_revision: Union[str, None] = '32c4aa90371d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('frosties', 'price',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               nullable=True)
    op.drop_column('frosties', 'sellable')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('frosties', sa.Column('sellable', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.alter_column('frosties', 'price',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               nullable=False)
    # ### end Alembic commands ###
