"""imgs nullable false

Revision ID: c0d0f3d7e8bf
Revises: 64d714c0f80c
Create Date: 2025-02-02 18:51:25.980916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0d0f3d7e8bf'
down_revision: Union[str, None] = '64d714c0f80c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('frosties', 'item_image',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('users', 'avatar',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'avatar',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('frosties', 'item_image',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
