"""add new enum values to order staus enum

Revision ID: cfbb0a56d960
Revises: 36b15a154ff1
Create Date: 2025-03-20 16:14:31.167211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfbb0a56d960'
down_revision: Union[str, None] = '36b15a154ff1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('payment_transaction_id', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('payment_status', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('refund_transaction_id', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('refund_status', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('idempotency_key', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'orders', ['idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='unique')
    op.drop_column('orders', 'idempotency_key')
    op.drop_column('orders', 'refund_status')
    op.drop_column('orders', 'refund_transaction_id')
    op.drop_column('orders', 'payment_status')
    op.drop_column('orders', 'payment_transaction_id')
    # ### end Alembic commands ###
